#! /usr/bin/sage -python
# -*- coding: utf8 -*-

"""
This is the skeleton of figures_all.py that will be automatically generated by 'create_all.py'
"""

import sys
from phystricks import *

from phystricksTRJEooPRoLnEiG import TRJEooPRoLnEiG
from phystricksQRXCooUmnlhkvh import QRXCooUmnlhkvh
from phystricksUREIooqNGBXtHg import UREIooqNGBXtHg

figures_list=[]

figures_list.append(TRJEooPRoLnEiG)
figures_list.append(QRXCooUmnlhkvh)
figures_list.append(UREIooqNGBXtHg)

def AllFigures():
    tests=main.FigureGenerationSuite(figures_list,first=0,title=u"demonstration pictures")
    tests.generate()
    tests.summary()

if __name__=="__main__":
    if "--all" in sys.argv :
        AllFigures()
    else:
        ProjPoly()
